### 1. Add superuser !!!OPTIONAL!!!
#OK!
#DC!
POST https://kecskecsecse.tk/addsu HTTP/1.1
#POST http://127.0.0.1:5001/addsu HTTP/1.1
content-type: application/json

{
    "username": "superuser",
    "password": "123456aA"
}


### 2. Login as post w JSON
#POST https://kecskecsecse.tk/API/login HTTP/1.1
POST http://127.0.0.1:5001/API/login HTTP/1.1
content-type: application/json

{
    "username": "superuser",
    "password": "123456aA",
    "remember": false
}


### 3. Add users
#OK!
#DC!
#POST https://kecskecsecse.tk/API/adduser HTTP/1.1
POST http://127.0.0.1:5001/API/adduser HTTP/1.1
content-type: application/json

{
    "username": "kunbela",
    "password": "1234567aA",
    "email": "kunbela@mail.com",
    "is_enabled": true,
    "is_superuser": false
}


### 3. Delete user !!!OPTIONAL!!!
#OK!
#DC!
#POST https://kecskecsecse.tk/API/deluser HTTP/1.1
POST http://127.0.0.1:5001/API/deluser HTTP/1.1
content-type: application/json

{
    "uid": 4
}


### 3/A. Update user !!!OPTIONAL!!!
#POST https://kecskecsecse.tk/API/updateuser HTTP/1.1
POST http://127.0.0.1:5001/API/updateuser HTTP/1.1
content-type: application/json

{
    "uid": 4,
    "email": "modified@mail.com",
    "settings": "{modified!}"
}


### 4. Add testbattery
#OK!
#DC!
#POST https://kecskecsecse.tk/API/addbattery HTTP/1.1
POST http://127.0.0.1:5001/API/addbattery HTTP/1.1
Content-Type: application/json

{
    "short_name": "proba-battery 3.",
    "name": "Tesztcsomag 3., alapvető funkciók tesztelésére",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "user_id": 6
}


### 4. Delete testbattery  !!!OPTIONAL!!!
#OK!
#DC!
#POST https://kecskecsecse.tk/API/delbattery HTTP/1.1
POST http://127.0.0.1:5001/API/delbattery HTTP/1.1
content-type: application/json

{
    "tbid": 4
}


### 5. Add survey
#OK!
#DC!
#POST https://kecskecsecse.tk/API/addsurvey HTTP/1.1
POST http://127.0.0.1:5001/API/addsurvey HTTP/1.1
content-type: application/json

{
    "title": "Egy névtelen felmérés",
    "is_anonymus": true,
    "is_active": true,
    "is_archived": false,
    "email_body": "A köremail szövege",
    "tbid": 5
}


### 5. Del survey !!!OPTIONAL!!!
#OK!
#DC!
#POST https://kecskecsecse.tk/API/delsurvey HTTP/1.1
POST http://127.0.0.1:5001/API/delsurvey HTTP/1.1
content-type: application/json

{
    "sid": 24
}


### 5/B. Add survey (named)
#OK!
#DC!
#POST https://kecskecsecse.tk/API/addsurvey HTTP/1.1
POST http://127.0.0.1:5001/API/addsurvey HTTP/1.1
content-type: application/json

{
    "title": "Egy nevesített felmérés - 2.",
    "is_anonymus": false,
    "is_active": true,
    "is_archived": false,
    "email_body": "A köremail szövege",
    "tbid": 7
}


### 6. Add client
#OK!
#DC!
#POST https://kecskecsecse.tk/API/addclient HTTP/1.1
POST http://127.0.0.1:5001/API/addclient HTTP/1.1
content-type: application/json

{
    "name": "Aladár",
    "email": "aladar@email.com",
    "is_archived": false,
    "survey_id": 29
}


### 6. Delete client !!!OPTIONAL!!!
#OK!
#DC!
#POST https://kecskecsecse.tk/API/delclient HTTP/1.1
POST http://127.0.0.1:5001/API/delclient HTTP/1.1
content-type: application/json

{
    "cid": 7
}


### 7. get all data in JSON
#OK!
#GET https://kecskecsecse.tk/API/admindata HTTP/1.1
GET http://127.0.0.1:5001/API/admindata HTTP/1.1


### 8. wipe database (except admin users)
#GET https://kecskecsecse.tk/API/wipedatabase HTTP/1.1
GET http://127.0.0.1:5001/API/wipedatabase HTTP/1.1



### 8. Logout user
#OK!
#GET https://kecskecsecse.tk/logout HTTP/1.1
GET http://127.0.0.1:5001/logout HTTP/1.1


### 10. Healthcheck
GET https://kecskecsecse.tk/healthcheck HTTP/1.1